// Automatically generated by astro-icon
// 991e01687893cb86202c68b17f5db0f4229f9054a78067e026577c9942f5e48b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "devdotto"
		| "github"
		| "linkedin"
		| "minutemailer"
		| "twitter";
}